//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28/11/2017 13:42:19
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Entidade
{
    public partial class Estoque {

        public Estoque()
        {
            this.Produtos = new List<Produto>();
            OnCreated();
        }

        public virtual long Id
        {
            get;
            set;
        }

        public virtual long Quantidade
        {
            get;
            set;
        }

        public virtual long MedidaId
        {
            get;
            set;
        }

        public virtual IList<Produto> Produtos
        {
            get;
            set;
        }

        public virtual Medida Medida
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
